language: android
jdk: oraclejdk8
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"

env:
  global:
    - EMULATOR_API_LEVEL=15
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    - android-$ANDROID_API_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL
    - sys-img-$ANDROID_ABI-android-$EMULATOR_API_LEVEL
  licenses:
    - android-sdk-.+
    - google-gdk-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_c75769befc95_key -iv $encrypted_c75769befc95_iv
    -in keystore.jks.enc -out keystore.jks -d
  - openssl aes-256-cbc -K $encrypted_c75769befc95_key -iv $encrypted_c75769befc95_iv
    -in fabric.properties.enc -out app/fabric.properties -d
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-15"
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "system-images;android-15;google_apis;armeabi-v7a"
  - sdkmanager --list
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses

before_script:
  - echo no | avdmanager create avd --force -n test -k "system-images;android-15;google_apis;armeabi-v7a"
  - "$ANDROID_HOME/tools/emulator -avd test -no-audio -no-window &"
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

before_deploy:
  - mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/600-series-ns-uploader.apk

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: s9II6aXk4RBKz4tSEs9ObRTJQKuw2Kg5brJ8HZCs5zWGL7LbN8IEHRpLJb79wm2DfCoonIj5xdNPFVtBN9GPbAGzxmthaeWmQjyB05s0VkUScYGfufSIi7DgRqvRxvBmq7o4WyNCZgZLvFSMUnZ3L9Ay+X7Qrl62fZkMgjlKybApceGRr5eIoEcrDhGz4+Lf5ABBZSXUP0+YlPZ9SHUANhqeWRSSmzOEBM9Mw8mlmJKRvfBu8i946RoousEOLh1y1+Qxdaw6hn2Ng6v8iTMJdAt66dk9VHz9B05AXz6wm8Q3RuVtMkoawJLKHTkIXM06Tl8HzOt0e68ojkDNWSmSgGPEAY157TRCQJXAFHkZuo3mQrgI+heHMj+nfMNaHpunl13stRCUj0OLsmziCVI/llvcSWPcRcibjg1J02JvIKIZOjv8aCUjMIYBif7U2MdHKklElvxhFYGwBTorg6urPu7t7ljy7r6bKm2Jn5l4/6IOXBzEw2i/fwhnumz/LDAvQB1WWGQkAIGGQvFK0x54dafAAK6ykx1y1Myw0mBf/Lp38Cdkuw9jOaeuf/kM+ih3mZzaCPHNklzmoPWnLSSLjj2ZUH/1BgEcSjmvcf242dmxnGeWCNHTfZgn6dDj6nJ6Db6Pcvckyc5+NuxntZvdAOInKECgIlN88E5xk0IEqzY=
  file: app/build/outputs/apk/release/600-series-ns-uploader.apk
  on:
    repo: pazaan/600SeriesAndroidUploader
    tags: true
    # Octokit options
    prerelease: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0283e844d525908106b2
    on_success: change
    on_failure: always
    on_start: false
